# 运行阶段：用 TARGETPLATFORM 让 buildx 自动匹配目标架构
FROM --platform=$TARGETPLATFORM qicfan/qms-build-base:latest

# 设置时区
ENV TZ=Asia/Shanghai
ENV PATH=/app:$PATH

# 添加用户和组
RUN addgroup -g 12331 qms && \
    adduser -D -u 12331 -G qms qms
RUN id qms
RUN echo 'qms ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
RUN mkdir -p /dev/shm && chmod 1777 /dev/shm

# 设置工作目录
WORKDIR /app

# 根据目标架构复制对应的二进制
ARG TARGETARCH
COPY build/${TARGETARCH}/QMediaSync .
COPY web_statics ./web_statics/
COPY scripts ./scripts/

RUN chmod +x /app/scripts/docker-entrypoint.sh
RUN chmod +x /app/scripts/watch_update.sh
RUN chmod +x /app/QMediaSync

VOLUME ["/app/config", "/media"]
EXPOSE 12333
EXPOSE 8095
EXPOSE 8094
CMD ["/app/scripts/docker-entrypoint.sh"]