# 运行阶段
FROM --platform=linux/arm64 qicfan/qms-build-base:latest
# 设置时区
ENV TZ=Asia/Shanghai
ENV PATH=/app:$PATH
ENV DB_HOST=localhost
ENV DB_PORT=5432
ENV DB_USER=qms
ENV DB_PASSWORD=qms123456
ENV DB_NAME=qms
ENV DB_SSLMODE=disable

# 添加用户和组
RUN addgroup -g 12331 qms && \
    adduser -D -u 12331 -G qms qms
RUN id qms
RUN echo 'qms ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
RUN mkdir -p /dev/shm && chmod 1777 /dev/shm

# 设置工作目录
WORKDIR /app

# 直接复制 workflow 编译好的 arm64 二进制
COPY QMediaSync .
COPY web_statics ./web_statics/
COPY scripts ./scripts/

RUN chmod +x /app/scripts/docker-entrypoint.sh
RUN chmod +x /app/scripts/watch_update.sh
RUN chmod +x /app/QMediaSync

VOLUME ["/app/config", "/media"]
EXPOSE 12333
EXPOSE 8095
EXPOSE 8094
CMD ["/app/scripts/docker-entrypoint.sh"]